week-3 assignments
learn-academy-2022-echo/week-3-assessment-addisdave pull request #1
Opened 2022-08-22 15:57 UTC by addisdave

# Submitting Week 3 Assessment

### ✅ Completed Files
Mark the following as confirmation that the files in this repository are complete.
- [ ] Coding Challenges
- [ ] Interview Questions
- [ ] React Debugging

### 📝 Feedback
If you would like specific feedback on a particular problem please leave details here:

2022-08-23 14:55 UTC, SunkissedQueen requested changes
Dawit, I see that there are some blockers on the code challenges. We can attempt to tackle those this morning. I will need to see all the tests and functions to complete this review. Suggestions for the interview questions: remember it is a conversation. Ensure you are not only giving definitions but also examples to show how you have used the tool.

2022-08-23 14:55 UTC, SunkissedQueen commented on react-debugging.html
nice

2022-08-23 14:55 UTC, SunkissedQueen commented on interview-questions.md
looking forward to these lecture

2022-08-23 14:55 UTC, SunkissedQueen commented on interview-questions.md
Consider what you want to incorporate into your interviews. Create a flow for yourself and share it on next week assessment. Things I am looking for more content to include an example of how you used the topic. Think making a conversation with the interviewer.

2022-08-23 14:55 UTC, SunkissedQueen commented on code-challenges.test.js
> +//Psudocode:
please include what information you need to get from the input to the output

2022-08-23 14:55 UTC, SunkissedQueen commented on code-challenges.test.js
Look over the structure of functions. Use a parameter vice the argument. The parameter will allow the function to be reusable.

2022-08-23 14:55 UTC, SunkissedQueen commented on code-challenges.test.js
> +
Are the node modules, package.json, and other files in the same directory?

2022-08-26 22:34 UTC, addisdave commented
check

2022-08-26 23:22 UTC, SunkissedQueen approved these changes
Dawit, you are approved. Thanks for working through these test and functions. As you see with practice, it becomes smoother. Keep a template of the test and then refactor it according to the question. The interview answers need more structure and content. The interview questions is a time for you to practice what you would do at an interview. Set up a flow: definition and examples.

2022-08-26 23:22 UTC, SunkissedQueen commented on code-challenges.test.js
> +const sumArray = (array) => {
Let's think about what you want to do with the array. What information do you need to get from the input to the expected output?

2022-08-26 23:26 UTC, merged